### ISSUE TITLE
Provide more linux binaries

### ISSUE THREAD

**Issue by bmarwell** [libretro/RetroArch#12266]
# First and foremost consider this:

- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

(btw) how do I get rights in IRC? Haven’t found a clue anywhere. Cannot message…

For most platforms, multiple versions (current, old, nightly) are provided.
For linux, only the current version is provided.
Because of https://github.com/libretro/RetroArch/issues/12262, I wanted to go back to 1.9.0.
However, the Ubuntu PPA's 1.9.0 is actually a 1.9.1 in disgues (yep, it says 1.9.0, but `--version` gives 1.9.1),
the snap store has no "previous" channel, app iamges are not available for older version (only current stable).
Haven’t checked flatpacks.

### Expected behavior

For e.g. windows, you have URLs like this:

* https://buildbot.libretro.com/stable/1.9.1/windows/x86_64/RetroArch-Win64-setup.exe

Also, multiple nightlies are availble:

* https://buildbot.libretro.com/nightly/windows/x86_64/

### Actual behavior

The linux URLs do not include a version:
* https://flathub.org/repo/appstream/org.libretro.RetroArch.flatpakref
* http://buildbot.libretro.com/nightly/linux/x86_64/RetroArch_Qt.7z

Using linux nightlies:

* https://buildbot.libretro.com/nightly/linux/x86_64/
… but they do not go back enought in time

Snapstore has no "old" channel:

```
name:      retroarch
summary:   RetroArch
publisher: hunterk (libretro)
store-url: https://snapcraft.io/retroarch
contact:   https://forums.libretro.com/
license:   GPL-3.0
[…]
snap-id:      7xMPaiM3yBx0npSKPNuTYNhzW4xI9CDk
tracking:     latest/stable
refresh-date: today at 08:40 CEST
channels:
  latest/stable:    1.9.1 2021-04-08 (453) 299MB -
  latest/candidate: 1.9.1 2021-04-08 (453) 299MB -
  latest/beta:      1.9.1 2021-04-08 (453) 299MB -
  latest/edge:      1.9.1 2021-04-12 (461) 299MB -
installed:          1.9.1            (453) 299MB -
```

### Bisect Results

[n/a]

### Version/Commit

m/a

### Environment information

- OS: linux, any
- Compiler: [does not apply]

**Comment by hizzlekizzle** [comment]
For the AppImages, that's just because they're relatively new (for us). Moving forward, they will have archived stables, which we have for 1.9.1: https://buildbot.libretro.com/stable/1.9.1/linux/x86_64/, just like for Windows.

AFAIK, the other outlets (snap, flatpak, PPA), don't provide any good way of keeping old versions around, unfortunately.

**Comment by bmarwell** [comment]
@hizzlekizzle they do.

Example output of IntelliJ's snap:

```

**Comment by bmarwell** [comment]
This is your flatpak repo. Sadly, the subject does not always contain a version (like 1.9.0).

```
21:48 $ sudo flatpak remote-info --log flathub org.libretro.RetroArch

RetroArch - Frontend for emulators, game engines and media players

        ID: org.libretro.RetroArch
       Ref: app/org.libretro.RetroArch/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 1.9.1
   License: GPL-3.0
Collection: org.flathub.Stable
  Download: 270,4 MB
 Installed: 470,2 MB
   Runtime: org.kde.Platform/x86_64/5.14

       Sdk: org.kde.Sdk/x86_64/5.14
    Commit: 6206dc3fed228d43cfe446afc3dad0d8a44a546632af3acd18444a803ce1cc50
    Parent: b22f81ea375aa64aeb885268357d32df7df81d4da1f7ce498eb97dc91c53b6f8
   Subject: v1.9.1 (#168) (1f357fde)
      Date: 2021-03-30 18:47:21 +0000
   History: 

    Commit: b22f81ea375aa64aeb885268357d32df7df81d4da1f7ce498eb97dc91c53b6f8
   Subject: Add libusb (#167) (ff466df3)
      Date: 2021-02-28 19:47:52 +0000

    Commit: 96a53026110974a42f317b13cc1762ddf5a7cc8f17532c6089e18f526d3e1d71
   Subject: Fix update list (3039dea0)
      Date: 2020-08-10 00:45:14 +0000

    Commit: 77d92f1294c9fc3fe00fbdd10416f985ff5012d52f828ff62f536600400f1237
   Subject: Switch to SDL2 (64b84f89)
      Date: 2020-06-25 02:24:11 +0000

    Commit: ed56907d1db3f7de99fb5b5483d934ea8c3689a5ae1cc504af279e7da5ade061
   Subject: Fix commit hash (4f3004a3)
      Date: 2020-06-24 02:41:58 +0000

    Commit: 0c57bc4e98949256f89da2411ad6a09e6dec4de72f4a9a7d968aa811b031f1ba
   Subject: Update to v1.8.7 (c448811f)
      Date: 2020-05-18 15:40:31 +0000

    Commit: 25209119fc5969b3ddbf7b7b539935824c30b6486e4a671e8829fd3e0b104432
   Subject: input_joypad_driver: Switch to udev (a05ef853)
      Date: 2020-05-06 08:55:38 +0000

    Commit: d1287f937194037615294745effb95fc4a82d478413270005ed14086eb00c5df
   Subject: Delete screenshot-2.png (8c7ff86d)
      Date: 2020-05-06 07:18:10 +0000

    Commit: 68a1eeb7640393c243ebdba2d99865dc4e79bf2dadd9c95a6fcaa0d6f80817a3
   Subject: Fix hashes (ba8bb348)
      Date: 2020-03-22 05:16:31 +0000

    Commit: 84c65d911fd678840bd8125979cf2a6a1e8b9ce416acbc53cb3a5b94ee8bb9cd
   Subject: retroarch-joypad-autoconfig: Update to the latest (e29d9c3b)
      Date: 2020-03-02 22:21:35 +0000

    Commit: 60bbd153502233a7fb7fa9ac4876f3e64fe8d0f3e1b08185c996882a010d3bc9
   Subject: docs: Add section about known issues (194ca13d)
      Date: 2020-02-22 15:29:28 +0000

    Commit: 4c33ce0159ed9f1fe0f15f55cf23778d2f946eeb43d80650bbb49acbafd939a5
   Subject: xrandr: Add xrand (2a3ece44)
      Date: 2020-01-23 17:15:50 +0000

    Commit: 7c9fb0dcb0770f943312031a626da80f07f61ee5b6ecf95c67245d90e84df43e
   Subject: udev: Update to v244 (95c1b027)
      Date: 2020-01-22 19:32:32 +0000

    Commit: 45bcc905b499a80c9407706cf9165c4aa62b03b45c5d38ceb94495236f92dd1a
   Subject: metadata: Fix release date (7b14fd55)
      Date: 2020-01-18 23:42:14 +0000

    Commit: 26a6d1ca248ed2ff38c2a2b5245f0020f17bec0f0d692730efb14b578b215ba3
   Subject: Update shared-modules (e18ecf48)
      Date: 2020-01-18 21:10:36 +0000

    Commit: de8151215df96c70569c4ca245bf9a02eb2b207f0ea02740814b0e51532188db
   Subject: retroarch: Update to 1.8.4 (c615bcd7)
      Date: 2020-01-17 20:11:34 +0000
```
