### ISSUE TITLE
Windows Arm64 releasee

### ISSUE THREAD

**Issue by Xazax-hun** [libretro/RetroArch#15975]
It would be nice to be able to download a native installer for Windows on Arm64.

**Comment by gorban** [comment]
Bump. Especially with the new Qualcomm X Elite.

**Comment by hizzlekizzle** [comment]
We currently don't have any ARM runners to be able to natively compile Windows or Linux on ARM. Github is adding some soon, though, so we might be able to get some automated builds going when they're widely available.

**Comment by Wunkolo** [comment]
I've personally used [this](https://github.com/ilammy/msvc-dev-cmd) in my GitHub workflows to cross-compile ARM64 builds. This was enough to do an ARM64 build on the x64-based runner.
```yaml
      - name: Configure msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64_arm64
```
