### ISSUE TITLE
Using continuous integration

### ISSUE THREAD

**Issue by Holzhaus** [libretro/RetroArch#1868]
How about using continuous integration like [travis-ci](http://docs.travis-ci.com/user/getting-started/). This way, Pull Requests and new commits will be automatically checked for compilation errors.

All you need is to allow *travis-ci* to access your repo and add a `.travis.yml` in the root of your directory, for example:
```yaml
language: cpp

script: ./configure && make && make install

compiler:
  - gcc
  - clang
```
